### ISSUE TITLE
ConfigTool usage - no way to make it running like v2.0

### ISSUE THREAD

**Issue by augurarte** [openlab/OGDI-DataLab#24]
In version 2.0 the ConfigTool prepared your Storage accounts to run the application against your own datasets, in this version there are several errors related to this configuration. Firs it only runs properly against Storage account and original service (ServiceURI) and if you use your own service browser URI you will get always the same error (due an exception because it can'not find the model (table sotorage with the curren configuration).

Documentation in the wiki area is confusing, mixing concepts and names that doesn't exist in the current version (4 or 5). InteractiveSDK is the name of the namespace but not the projects, and the page of the Service Topology is confusing either due there is like a Hosted Service for the Data Service but in the real solution this is included into the Web Role (DataBrowser)

Is there any way to create and configure Table Storage using our accounts and load only our datasets or is only available for using the current datatasets and configurations from http://data.govdata.eu

**Comment by remiolivier** [comment]
To load only your datasets :
- Setup your web.config in the ConfigTool project with your configuration storage
- Run the ConfigTool project and setup your datasets (based on one or multiple datastorages)
- The OGDI DataLab project is now configured you just need to load your data with the DataLoader

The ServiceURI has to be based on your hosted DataService project typically http://[name].cloudapp.net:8080/v1/ in v5 in order to display your datasets.

About names confusion a new documentation is coming explaining in details the steps to configure and run OGDI DataLab with your own datasets.

**Comment by augurarte** [comment]
Thanks Remiolivier,
- Web.config in my ConfigTool project is set up to my configuration storage, that by now is the same storage that the data account, I supposse this could be as it's mentioned in the documentation (in github because in v2.0 I used 2 storage accounts).
- I have used already ConfigTool and configured the data storage (for one dataset), I'm testing agains that
- I'm currently using DataLoaderGuiApp for trying to upload some basic .csv datasets, I've tryed with a downloaded .csv from http://dev.govdata.eu (with this one: http://dev.govdata.eu/DataBrowser/estOpenData/Toodrid#param=NOFILTER--DataView--Results ), and with one created by me with some records (about spanish municipalities) and the DataLoader always ends with the same error, first this one "Index (zero based) must be greater than or equal to zero and less than the size of the argument list." and at the end this other "Input string was not in a correct format." We are now debugging to try to see the problems but by now it seems DataLoaderGui is not very pulished, I remember version 2.0 working fine. In the case of .csv files we are using we have tested that are properly constructed, only header, and some rows with simple data types.

**Comment by javimaravillas** [comment]
Hi,
I´m debuging with Augurate and in the file CsvEntityProducer.csv on line 227, when its try to get the xml tag of the cfg (that the dataloadergui generates), its get that empty because <NameProperties /> is empty, here is the a few lines of the autogenerated cfg file:

<PlacemarkParams>
      <LatitudeProperty>LATIT</LatitudeProperty>
      <LongitudeProperty>LONG</LongitudeProperty>
      <NameProperties />
    </PlacemarkParams>

Could you say to us, what it expected to be in that tag?

Its fails when you set the option Bind to Maps, and the exception is in the line 232 of that file:

placemark.Add(new XElement(
                                    XNamespace.Get(DataLoaderConstants.NsKmlNew) + DataLoaderConstants.ElemNameName,
                                    new XCData(string.Format(_params.PlacemarkParams.NamePropertyFormatString ?? "{0}", names))));

NamePropertyFormatString and names is empty, so It launch the exception because name is empty, that it is empty because the tag <NameProperties> is empty.

Could you explain the behaviour or give a valid cfg file. With a valid CFG file, we could do this with the DataLoaderConsoleApp utility ;)

Thanks

**Comment by javimaravillas** [comment]
Hi,
We finally do this stuff!!! You have to set up a Text in the Map "Push Pin Text To", if not, it would fails.

I expected this could be for help for anyone else!

**Comment by remiolivier** [comment]
By default the checkbox "Bind to map" is active so you need to set up a text for pushpins that will be displayed on map. A dropdownlist appears if you click to a specified row on the "Push pin mapping" column. By selecting a value you can report it to the text field : "{0} <br /> {1}" for example.

You can also disable "Bind to map" so you don't need to set up a text and the map will not appear on OGDI DataLab. This option is usefull especially when there is no coordinates in a csv, you prefer the users create custom formats or some coordinates are invalid but you need to upload them.

**Comment by nikg** [comment]
@remiolivier Remi, should we change the "Bind to map" behavior to be unchecked by default? I think this has been an issue for folks unfamiliar with the DataLoader, as it's not intuitive when it's checked (and no lat/lon values are present).

Nik

**Comment by remiolivier** [comment]
Yes it looks like a common mistake for people even for those who are familiar with the DataLoader
